// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAajEpHf3hrTE40n2T68ciIwORJxiBQyFA',
    appId: '1:1047584493580:web:ed1833064a24b53b831e29',
    messagingSenderId: '1047584493580',
    projectId: 'fir-assignmet',
    authDomain: 'fir-assignmet.firebaseapp.com',
    storageBucket: 'fir-assignmet.firebasestorage.app',
    measurementId: 'G-TBZBSCXD02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF-W_YKh1EMK3oGm1Er0x-uSDnfi-viKo',
    appId: '1:1047584493580:android:63494a7c5d846819831e29',
    messagingSenderId: '1047584493580',
    projectId: 'fir-assignmet',
    storageBucket: 'fir-assignmet.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAajEpHf3hrTE40n2T68ciIwORJxiBQyFA',
    appId: '1:1047584493580:web:770f0809dc420613831e29',
    messagingSenderId: '1047584493580',
    projectId: 'fir-assignmet',
    authDomain: 'fir-assignmet.firebaseapp.com',
    storageBucket: 'fir-assignmet.firebasestorage.app',
    measurementId: 'G-94P7GYGSB2',
  );
}
